# SEO Values
title: RAC
tagline: The best movement checks ...
description: The best movement checks ...
url: https://reaperlab.github.io/RAC/


# GitHub Values
github:
  owner_name: ReaperLab
  owner_url: https://github.com/ReaperLab
  repository_url: https://github.com/ReaperLab/RAC

show_downloads: true
show_header: true
remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
